### ISSUE TITLE
SIMD capacity not detected by ScanByte, using scalar fallback

### ISSUE THREAD

**Issue by oniehuis** [jakobnissen/ScanByte.jl#7] opened 2022-07-02 14:45 UTC
I receive a warning when loading the package ScanByte (v. 0.3.2) in Julia 1.8.0-rc1 (2022-05-27) (experimental 64-bit installer for macOS ARM (M-series Processor)) on a MacBook Pro with Apple M1 Max processor and Mac OS 12.4:

julia> using ScanByte
┌ Warning: SIMD capacity not detected by ScanByte, using scalar fallback
└ @ ScanByte ~/.julia/packages/ScanByte/cr4PT/src/ScanByte.jl:11

Any idea how to address the problem?

**Comment by jakobnissen** [comment] 2022-07-04 08:04
Duplicate of #2 . The warning happens because ScanByte is optimised for x86 chips with SSSE3 or AVX2 instruction sets. The new M1/M2 Mac chips use Armv8 and do not have these instructions.
I have just removed the warning from the version on master. Hopefully some time in the future I can add Armv8 functionality.

**Closed by jakobnissen** 2022-07-04 08:04 UTC
