### ISSUE TITLE
SIMD Capacity not detected on M1

### ISSUE THREAD

**Issue by f-ij** [jakobnissen/ScanByte.jl#5] opened 2022-06-09 12:06 UTC
I'm getting the following error on my M1 MacBook:
┌ 
Warning: SIMD capacity not detected by ScanByte, using scalar fallback
└ @ ScanByte ~/.julia/packages/ScanByte/eOQJf/src/ScanByte.jl:11

**Comment by jakobnissen** [comment] 2022-06-09 13:08
Duplicate of #2 .
The problem is that I don't have a computer with an armv8 chip, so I can't test and develop the code.

**Closed by jakobnissen** 2022-06-09 13:08 UTC
